### ISSUE TITLE
How to send a response to a write()?

### ISSUE THREAD

**Issue by ragjunk** [mafintosh/noise-network#1]
Hi,

noise-network is nice library that gets away with dealing with IP addresses and ports to discover and communicate with peers. I am experimenting with it to build a secure communication channel between two parties, but I am not able to figure out how the "server" can respond to client's write() request. In the example provided, encryptedStream.on() allows the server to receive the data. Is there a way to send the response back to the client, say acknowledging the request?

`server.on('connection', function (encryptedStream) {
  console.log('new encrypted stream!')

  // encryptedStream is a noise-peer stream instance
  encryptedStream.on('data', function (data) {
    // What should be done here to respond to the client?
  })
})`

**Comment by mafintosh** [comment]
You should be able to do that using encryptedStream.write(data) (it's a writable stream as well) :)
