### ISSUE TITLE
client does not connect any more

### ISSUE THREAD

**Issue by robertkowalski** [mafintosh/noise-network#4]
my noise client does not connect any more, testable with hypercore-benchmark:

https://github.com/bitfinexcom/hypercore-benchmark/blob/master/p2p-noise-client.js#L19-L21

the callback from the read method is never called. 

probably more important, on the server side the `connection` event is not emitted

it just eats a lot of cpu:

```
1560280498874 4994 'cpu: 113.6% | rss: 561 MB (6.5%) | heap: 51 MB / 95 MB (53.9%) | ext: 1.4 GB | delay: 42 ms | 00:00:10 | loadavg: 2.13, 2.08, 2.02'
1560280503874 4998 'cpu: 166.5% | rss: 639 MB (7.4%) | heap: 95 MB / 148 MB (63.8%) | ext: 2.7 GB | delay: 56 ms | 00:00:15 | loadavg: 2.20, 2.10, 2.02'
1560280508880 5000 'cpu: 187.5% | rss: 750 MB (8.7%) | heap: 133 MB / 196 MB (67.8%) | ext: 3.9 GB | delay: 26 ms | 00:00:20 | loadavg: 2.34, 2.13, 2.03'
```

```
$ node -v
v10.14.1
```

```
    "hypercore": "^7.2.0",
    "length-prefixed-message": "^3.0.3",
    "noise-network": "^1.0.2",
```

**Comment by mafintosh** [comment]
Should be fixed in master. @robertkowalski if that's not the case let me know.
